### ISSUE TITLE
The colors are wrong

### ISSUE THREAD

**Issue by memeplex** [idleberg/base16-pygments#1]
For example, the correct default-dark colors are:

```
BACKGROUND = "#181818"
CURRENT_LINE = "#282828"
SELECTION = "#383838"
FOREGROUND = "#f8f8f8"
COMMENT = "#585858"
RED = "#ab4642"
ORANGE = "#dc9656"
YELLOW = "#f7ca88"
GREEN = "#a1b56c"
AQUA = "#86c1b9"
BLUE = "#7cafc2"
PURPLE = "#ba8baf"
```

yet the ones in your repo are very different (maybe outdated?).

**Comment by idleberg** [comment]
What's your definition of _correct_? As far as I can tell, the base16 templates haven't been changed in years. As mentioned in the README, issues and pull request should go to the base16-builder repository.

**Comment by memeplex** [comment]
I don't think there is any subjectivity in my opinion here: the output above is obtained running your templates against the official base16 builder. Also, just take a look at the base16 default color table.
